<?php

namespace app\modules\preview;


use Yii;

class PreviewModule extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\preview\controllers';

    private $app_balance;

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }


}
