<?php

namespace app\modules\car\models;

use app\modules\helper\HelperModule;
use Yii;

/**
 * This is the model class for table "car".
 *
 * @property int $id
 * @property string $name
 * @property string $number
 * @property int $online
 * @property int $status
 * @property int $num_tableled
 * @property string $date_cr
 * @property string $secret
 * @property string $ip
 */
class Car extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    const  ST_ON = 1;
    const  ST_OFF = 0;


    public static function tableName()
    {
        return 'car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'number', 'date_cr'], 'required'],
            [['online', 'status', 'num_tableled'], 'integer'],
            [['date_cr'], 'safe'],
            [['name','ip'], 'string', 'max' => 45],
            [['secret'], 'string', 'max' => 10],

            [['number'], 'string', 'max' => 9],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'number' => 'Number',
            'online' => 'Online',
            'status' => 'Status',
            'num_tableled' => 'Num Tableled',
            'date_cr' => 'Date Cr',
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->date_cr = HelperModule::convertDateToDatetime();
    }
}
