<?php

namespace app\modules\bid\models;

use app\modules\reklamir\models\Reklamir;
use app\modules\url\models\Url;
use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "bid".
 *
 * @property int $id
 * @property int $account_id
 * @property int $val
 * @property int $minute_id
 * @property int $hour_id
 * @property int $mount_id
 * @property int $year_id
 * @property int $day_id
 * @property int $reklamir_id
 * @property int $time_id
 *
 *
 *
 */
class Bid extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bid';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['val', 'minute_id', 'hour_id', 'mount_id', 'year_id','day_id','reklamir_id','time_id'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'account_id' => 'Account ID',
            'val' => 'Val',
            'minute_id' => 'Time ID',
            'hour_id' => 'Hour ID',
            'mount_id' => 'Mount ID',
            'year_id' => 'Year ID',
        ];
    }

    public function getReklamir_r(){
        return $this->hasOne( Reklamir::class, ['id' => 'reklamir_id']);
    }

    public function beforeSave($insert)
    {
        $this->time_id = strtotime( $this->day_id .'-'.$this->mount_id.'-'.$this->year_id . ' ' . ($this->hour_id-1).':'.$this->minute_id );
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $rec = new BidLog();
        $rec->reklamir_id = $this->reklamir_id;
        $rec->time_id = $this->time_id;


        $rec->save();
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
