<?php
/**
 * Created by PhpStorm.
 * User: heltru
 * Date: 04.03.2018
 * Time: 6:31
 */

namespace app\modules\app\app;


use yii\base\Model;

class FormData  extends Model
{

    const  T_Q = 'quick_view';


    public $car_id;
    public $phone_email;
    public $phone;
    public $email;
    public $text;
    public $count_view;
    public $number_car;
    public $type = self::T_Q;

    public function load($data, $formName = null)
    {
        /*
       *  phone_email ,
          text ,
          count_view ,
       * */
        if (isset($data['text']) && $data['text']){
            $this->text = $data['text'];
        }
        if (isset($data['count_view']) && $data['count_view']){
            $this->count_view = $data['count_view'];
        }
        if (isset($data['number_car']) && $data['number_car']){
            $this->number_car = $data['number_car'];
        }
        if (isset($data['phone']) && $data['phone']){
            $this->phone = $data['phone'];
            $this->formatPhone();
        }


        return (boolean) (string)$this->text &&  (int) $this->count_view >= 60;
     //   return parent::load($data, $formName); // TODO: Change the autogenerated stub
        /*  $validator = new EmailValidator();
          if (! $validator->validate($phone_email, $error)) {
              //phone
          } else {

          }*/

       // return
    }

    public function rules()
    {
        return [

             //   [  ['phone_email'], 'required'],
            ['phone','string'],
            ['email','email'],
            ['text','string'],
           ['count_view','car_id','integer']
           // ['password', 'validatePassword'],
        ];
    }

    private function formatPhone(){
        $this->phone = str_replace(' ','', $this->phone);
        $this->phone = str_replace([' ','(',')'],['','',''], $this->phone);
    }

    public function getSumm(){

        return ( ( (int)$this->count_view )  / 6 );
    }

}