<?php

namespace app\modules\balance;

use app\modules\app\app\AppBalance;
use Yii;

class BalanceModule extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\balance\controllers';

    private $app_balance;

    public function init()
    {
        $this->app_balance = new AppBalance();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getBalance(){

        return $this->app_balance->getBalanceByCurrAccount();
    }
}
